# GitHub Sponsors / Funding configuration
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: wildfirebill
# patreon: wildfirebill
# open_collective: wildfirebill-ai
# ko_fi: wildfirebill
# tidelift: npm/hivestack
# community_bridge: wildfirebill-ai/hivestack
# liberapay: wildfirebill
# issuehunt: wildfirebill-ai/hivestack
# otech: wildfirebill
# custom: https://github.com/sponsors/wildfirebill